spring:
    application:
        name: demo
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password: 
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
    h2:
        console:
            enabled: true
            path: /h2-console

logging:
  level:
    '[com.example.ligan]': DEBUG
    '[org.springframework]': DEBUG
